Fixed the bug of element value
fastnlp/fastNLP pull request #436
Opened 2022-12-08 06:18 UTC by go-with-me000

Description：Fixed the bug of elment value

Main reason: 针对会议所提出的要求进行修改

Checklist  检查下面各项是否完成

Please feel free to remove inapplicable items for your PR.

-	[y] The PR title starts with [$CATEGORY] (例如[bugfix]修复bug，[new]添加新功能，[test]修改测试，[rm]删除旧代码)
-	[y] Changes are complete (i.e. I finished coding on this PR)  修改完成才提PR
-	[y] All changes have test coverage  修改的部分顺利通过测试。对于fastnlp/fastnlp/*的修改，测试代码**必须**提供在fastnlp/test/*。
-	[y] Code is well-documented  注释写好，API文档会从注释中抽取
-	[y] To the my best knowledge, examples are either not affected by this change, or have been fixed to be compatible with this change  修改导致例子或tutorial有变化，请找核心开发人员

Changes: 逐项描述修改的内容
- 添加了to_list
- 对于四个框架的fill_value进行了修改
- 对于apply_to_collection进行修改并测试
- 让value兼容float和List
Mention: 找人review你的PR

@修改过这个文件的人
@核心开发人员

2022-12-08 08:42 UTC, yhcc commented on fastNLP/core/callbacks/more_evaluate_callback.py
> +        logger.info("以下属于MoreEvaluateCallback:")
不要使用中文打印信息，可能在某些服务器上会导致乱码

2022-12-08 08:53 UTC, yhcc commented on fastNLP/core/metrics/backend/jittor_backend/backend.py
> +from spyder_kernels.utils.lazymodules import numpy
为啥需要这个咧？

2022-12-08 08:53 UTC, yhcc commented on fastNLP/core/metrics/backend/jittor_backend/backend.py
> +    def to_list(self, tensor) -> Union[float, List]:
修改一下，只能return list

2022-12-08 08:56 UTC, yhcc commented on fastNLP/core/metrics/bleu.py
> +        self.register_element(name="pred_len", value=[0], aggregate_method='sum', backend=backend)
这个如果就是single value，就直接使用数字吧。

2022-12-08 09:05 UTC, yhcc requested changes

2022-12-08 09:05 UTC, yhcc commented on tests/core/metrics/test_bleu_paddle.py
> +if _NEED_IMPORT_ONEFLOW:
如果在同一个文件中测试了三个backend，文件名中就不要包含了paddle了吧，文件名中包含框架名称的情况是指这个测试只包含这个backend的测试。

2022-12-08 09:05 UTC, yhcc commented on tests/core/metrics/test_element.py
> +    print(results)
这里的print就删掉吧，或者修改为某种assert？

2022-12-09 09:34 UTC, go-with-me000 commented on tests/core/metrics/test_bleu_paddle.py
> +        metric.update([predictions], [references])
这是指predictions
包括多条待预测的语句吗？

2022-12-10 13:44 UTC, merged